/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni/jni.h"
/* Header for class rtk_RtkMethod */

#ifndef _Included_rtk_RtkMethod
#define _Included_rtk_RtkMethod
#ifdef __cplusplus
extern "C" {
#endif
	

/*
* Class:     rtk_RtkMethod
* Method:    initrtcm
* Signature: (Lrtk/model/RtcmT;)I
*/
JNIEXPORT jint JNICALL Java_rtk_RtkMethod_loadRtkJni
	(JNIEnv *, jobject,jobject);

JNIEXPORT jint JNICALL Java_rtk_RtkMethod_pntpos
(JNIEnv *, jobject, jobjectArray, jint, jobject);

JNIEXPORT void JNICALL Java_rtk_RtkMethod_testSsat
(JNIEnv *, jobject, jobject);

/*
* Class:     rtk_RtkMethod
* Method:    rtkpos
* Signature: (Lrtk/model/RtkT;[Lrtk/model/ObsdT;ILrtk/model/NavT;)I
*/
JNIEXPORT jint JNICALL Java_rtk_RtkMethod_rtkpos
(JNIEnv *, jobject, jobject, jobjectArray, jint, jobject,jint);

/*
* Class:     rtk_RtkMethod
* Method:    rtkinit
* Signature: (Lrtk/model/RtkT;Lrtk/model/PrcoptT;)V
*/
JNIEXPORT void JNICALL Java_rtk_RtkMethod_rtkinit
(JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_rtk_RtkMethod_convrnx
(JNIEnv *, jobject, jstring, jstring, jstring, jlong);

JNIEXPORT jint JNICALL Java_rtk_RtkMethod_postpos
(JNIEnv *, jobject, jstring, jstring, jstring, jstring, jdouble, jdouble, jdouble, jobject,jint );

JNIEXPORT void JNICALL Java_rtk_RtkMethod_addRtkMap
(JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_rtk_RtkMethod_delRtkMap
(JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
